entrypoint: bundle exec rackup --port $PORT
# env: flex
runtime: ruby27
# automatic_scaling:
#   min_num_instances: 1
#   max_num_instances: 8

basic_scaling:
 max_instances: 10
 idle_timeout: 5m


beta_settings:
  cloud_sql_instances: unify-311918:us-west2:unify-sql

env_variables:
  SECRET_KEY_BASE: 0e127016dff33c942b52096d5dd185124b5f2c8205aa13feea18ff36851b626d9db331f0b0cac4b007d8497c7a484028f2a00aac6ba76f39dbd4355336c5f36f